### ISSUE TITLE
3D world looks cross-eyed on Google Cardboard

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#1]
This seems to have to do with the settings a Cardboard transmits to the Phone by the QR Code. [Here](https://www.google.com/get/cardboard/viewerprofilegenerator/) is where cardboard manufacturers create those settings to get Googles QR Code. The keyword here is _IPD_ (interpupillary distance), see [here](https://www.reddit.com/r/GoogleCardboard/comments/38k170/everything_on_google_cardboard_is_cross_eyed_to/) or [here](https://mentaljetsam.wordpress.com/2015/06/17/changing-google-cardboard-ipd-interpupillary-distance/) for example.
@zumbam was looking into this and found a fix that makes it look nice again (in both the Google Demo as well as the cardboard-branch we got from Flo) on the _Mr. Cardboard_ glasses we are using. The fix is to place 0 instead of 0.5 here:

![screen_shot_2015-10-16_at_20_53_34](https://cloud.githubusercontent.com/assets/5141792/10550769/12383748-7449-11e5-8b19-fb82782a9127.png)

@zumbam, maybe you can make this change and commit it to the cardboard branch? If you write #1 in the commit message this issue will automatically be referenced.

**Comment by tsiliakis** [comment]
Shouldn't this be marked as fixed ?

**Comment by benjaminaaron** [comment]
@zumbam hasn't committed the change to the cardboard branch yet :smiley:

**Comment by zumbam** [comment]
Sorry I forgot it :) 

But it`s not fixed at all.
My Solution i think is only an fix for the Nexus 6 or other devices with an height of 55 mm. 
When i do this fix above i subtract just the 5 mm from the Cardboard settings (60 mm height) which get set by reading the QR code of Mr Cardboard.
So its more an emergency solution.
This is why i won`t commit is .I think its better finding an solution for all devices.

So @benjaminaaron should I realy commit it?

**Comment by zumbam** [comment]
You can use this Cardboard Profil till I find a real solution
It`s created only for Nexus 6 with some values I find in the net.
![qr_viewer_profile](https://cloud.githubusercontent.com/assets/10027929/10560633/0a64cefa-7511-11e5-8211-20a3230792c6.png)

**Comment by zumbam** [comment]
I find out what the problem is.Florian put the wrong prefab of the camera into the szene.
We have to put main camera prefab into the scene than there is an option to choose the to develope
device.
<img width="207" alt="bugpick" src="https://cloud.githubusercontent.com/assets/10027929/10561123/ea0daa24-751e-11e5-9fb3-8b203437f380.PNG">

more informations about the settings to start with vr in the link below 
https://www.bing.com/videos/search?q=how%20to%20make%20an%20vr%20app%20with%20unity&qs=n&form=QBVR&pq=how%20to%20make%20an%20vr%20app%20with%20unity&sc=0-16&sp=-1&sk=#view=detail&mid=B9134E081655996F5136B9134E081655996F5136

Should I change this in the cardboard branch to or should we just do it in our project

**Comment by benjaminaaron** [comment]
I see. I find it strange that there is even an option to choose screen size in Unity. I would think to set these parameters is _only_ the task of the [Cardboard app](https://play.google.com/store/apps/details?id=com.google.samples.apps.cardboarddemo) on the phone that knows them through scanning the QR code :calling: 
Anyway, since we will continue working on the master branch and not the cardboard branch, it's not so important to fix it on the cardboard branch... unless of course for experimentation and as reference to use later? :smiley: 
Later, when we add cardboard-stuff to the master branch we can make it right from scratch and put the correct main camera prefab (what's a prefab?) into the scene...

**Comment by zumbam** [comment]
It's an template for combined objects 
for example the main camera.
In this prefab in is normal head camera and the two combined vr cameras 
with the prefab you can drag all 
both of these with setted skrip etc.
in the scene as often you want

another example is in roll a ball the rotating cubes

**Comment by zumbam** [comment]
And i feel the same there must be an better way in the other apps in the store it's working with all handys and cardboards
maybe you load the right build for especialy your phone i doubt it😂

**Comment by hacklschorsch** [comment]
@zumbam true. We (accu:rate) were on a Nexus 5. Finding a way to make this work on different cardboard/mobiles is key should we later want to publish to the Play store. Which we are going to want. For advertising (for accu:rate as well as HM) & effin' great justice

**Comment by benjaminaaron** [comment]
Closing this for now.
