### ISSUE TITLE
Have a start and in-game menu

### ISSUE THREAD

**Issue by tsiliakis** [benjaminaaron/SumoVizUnity#10]
When the app starts a menu should be displayed where the user can:
- Select the scenario
- Modify some app options
- View some information about the app

The menu should be navigated via head gestures. If you have any suggestions regarding the menu or its structure post a comment. 

To clarify: I was thinking about a start-up menu with basic head controls like the one in the Google Cardboard App, where you navigate by moving your head and 'looking' at the items.

![Example](http://cnet1.cbsistatic.com/hub/i/r/2014/07/15/43867400-efe2-46c7-8d1b-64f362f7e32b/resize/770x578/81d93009240fa5289e95b5c2ea2d2dd9/google-cardboard-interface.png)

Depends on #13 .

**Comment by zumbam** [comment]
We got allready an file chooser but i think this one is 
not useable with the cardboard

we should make an chooser which contains only on folder 
where the file all are in so its not to complex to use with the cardboard

to the points below app options are maybe the trajectories with 
the cardboard its really annoying if there are buttons in the view 

these options i think should be set before in a menu( idee above)
 not in the simulation like in the develop branch

**Comment by zumbam** [comment]
I will try to make the HUD the in game menu
I want to make important values visible.
thinks like count of person in tent 
And buttons like:
change szenario( jump back to main menu)
Maybe play / pause button
later walk / stand button (If we want to walk through the tent)

So if someone got anythink which is importing i forgot please make an comment

**Comment by benjaminaaron** [comment]
Closing all issues as we move to redmine for issue tracking on vadere _and_ unity
