### ISSUE TITLE
IDmappings.config

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#11]
Sub task of #3 and #5.
Create a file called **IDmappings.config** that tells unity what kind of 3D objects to create based on the 2D objects in Vadere. @Lesya91, can you make one and put it under Assets/Data on the master branch?

**Comment by benjaminaaron** [comment]
Prof. Köster said today its ok if we change Vadere source code. That means we could also add a **name** attribute to all objects and use that in unity instead of mapping IDs... or let's stick with mapping IDs? What do you think @Lesya91, @Mercorrius, @tobibi100 and Benni?

**Comment by Lesya91** [comment]
I think we can start with IDs now (for the first Sprint) and then maybe try the other way

**Comment by karimbk** [comment]
Good news! I think it makes really more sense to add a "name"-attribute. It will make life easier for all of us. We win on time (with IDs, you have to look back and see if it was the right one many times while programming) and efficiency doing it this way (with the IDs it is easy to confound the objects).

**Comment by TobiasHoefer** [comment]
I would stick with IDs. We have a small amount of different objects right now. If its such a pain with IDs we can do the changes in the second sprint.

**Comment by benjaminaaron** [comment]
Cool, let's stick with IDs for now and revisit the question in sprint #:two: 
Closing this issue for now.
