### ISSUE TITLE
Look into and implement head tracking

### ISSUE THREAD

**Issue by tsiliakis** [benjaminaaron/SumoVizUnity#13]
Look into and implement the functionality to register head movement and be able to "select" items.

**Comment by benjaminaaron** [comment]
@zumbam has some ideas for this.

**Comment by hacklschorsch** [comment]
I believe there's code for some approach that does that in the [Google Cardboard SDK for Unity demo project](https://developers.google.com/cardboard/unity/get-started).

**Comment by tsiliakis** [comment]
Thanks for the tip @hacklschorsch , already working with that :)

**Comment by benjaminaaron** [comment]
I believe this was achieved together with #14? Please reopen if I understood it incorrect.

**Comment by tsiliakis** [comment]
This is actually something different and related to menus, but let's keep this closed for now.
