### ISSUE TITLE
Implement a way to walk around the tent or teleport

### ISSUE THREAD

**Issue by tsiliakis** [benjaminaaron/SumoVizUnity#14]
This can be implemented by introducing "buttons" on the floor or by having some floating objects in the sky.

Depends on #13 .

**Comment by hacklschorsch** [comment]
Maybe related
- https://github.com/accu-rate/SumoVizUnity/issues/2
- https://github.com/accu-rate/SumoVizUnity/issues/3

**Comment by benjaminaaron** [comment]
@tsiliakis enabled walking (go and stop with touch on screen, walking direction is viewing direction) in 2d08f1a, nice work :+1:
Any chance for flying? :wink:

**Comment by tsiliakis** [comment]
Don't you ever sleep :smirk:
Flying 'should be' actually possible, it's still a bug in the current implementation, but I will look into it if there is demand for it.

**Comment by benjaminaaron** [comment]
Walking is achieved by @tsiliakis :+1: Reopen this issue if flying becomes a requested feature.
