### ISSUE TITLE
add cardboard mode to master branch

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#16]
Adding and testing it would be good though to do on a new branch before merging it onto master :wink:

**Comment by zumbam** [comment]
I wanna set moving to the camera with move it on click direction.
but to set up the moving i need to know where the terrain is getting created (to add an click event on it)
maybe someone of you have an idea which script it is or how else it gets created

**Comment by benjaminaaron** [comment]
In the method `loadScenarioFile` of _FileLoaderJSON_ the method `setTheme` is called on _GeometryLoader_. In that method the **groundplane** is set to a _Groundplane_ object that is defined in `Assets/Geometry/Groundplane.cs`. I already has a method called `OnMouseDown`, maybe you can use that...

**Comment by benjaminaaron** [comment]
Table is missing at this point but merge happened, closing this issue.
