### ISSUE TITLE
source documentation

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#18]
The C# sources need documentation. I would go with [Doxygen](http://doxygen.org) for now.
Will look into how to best configure the `Doxyfile` for our purpose.

**Comment by benjaminaaron** [comment]
@tsiliakis and @zumbam, can you document the C# code you wrote? You can use the same syntax you know from javadocs, see an example [here](https://github.com/benjaminaaron/SumoVizUnity/blob/master/Assets/Helper/FileLoaderJSON.cs#L132).

**Comment by tsiliakis** [comment]
Done in 038e3b4a5cdfaf47fda672ee0aef029ea2f40691

**Comment by benjaminaaron** [comment]
Thanks. Documentation isn't brought up by us tomorrow - I thought they might ask about it though :wink:

**Comment by benjaminaaron** [comment]
Closing all issues as we move to redmine for issue tracking on vadere _and_ unity.
