### ISSUE TITLE
find out how to assign new materials to objects

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#21]
Subtask of #4.
Decide if we should define a new theme or if we modify an existing one to fit our needs.

**Comment by zumbam** [comment]
I will modify an beerTenttTeme for the first sprint we can write an new on in the next one.
It will only include the new textures from @zippo7 for the normel beer tent walls.

**Comment by benjaminaaron** [comment]
Nice work @zumbam, let's close this issue and reopen later if necessary.
