### ISSUE TITLE
release a Sprint1 version

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#23]
Let's make a release (release-tag and uploading a ready-to-deploy `.apk` file) tomorrow prior to the presentation :tada: 
@tsiliakis, can the _Walking_ branch be deleted for now?
@zumbam, can Karim's _TentTheme_ branch be deleted?

**Comment by zumbam** [comment]
the TentTheme can be deleted

**Comment by benjaminaaron** [comment]
In case no one has any open commits before the Sprint1 release I would create the release later this evening :+1: 
The release-`.apk` is the one we should load onto the two phones for the presentation tomorrow. I will put it on the one I have and you can put it on yours @tsiliakis, ok?

**Comment by tsiliakis** [comment]
@benjaminaaron  I'd like to keep the branch for further development in sprint 2. 
Yeah, will do !

**Comment by tsiliakis** [comment]
Whats the ETA on the realease @benjaminaaron ?

**Comment by benjaminaaron** [comment]
It's already done, but I noticed that all walls are black on the sides, which looks very dark when you walk around with the cardboard on. So @zumbam is currently trying to fix that. After he fixed it (or not, no worries) I will make the release.

**Comment by tsiliakis** [comment]
Ok, lemme know ;)

**Comment by zumbam** [comment]
I trief to fix it but the problem seems to be about the creating of the uv vertices for painting the texture/material in extrude geometry
i haven't enought knolege about these think yet
maybe in sprint 2 someone can try to fix it
but i'm sure it will cost some days

**Comment by benjaminaaron** [comment]
No worries, thanks for trying. Let's fix this for the next sprint.
Release 1 is now [out](https://github.com/benjaminaaron/SumoVizUnity/releases/tag/Sprint1Release) :+1:
