### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#4]
@zippo7 is looking into textures that we need to model the tent, beer benches, beer tables and so on.

**Comment by zippo7** [comment]
Here are the textures I chose for our first demonstration purposes. They definetely don't look like a real Bierzelt yet but can be dowloaded for free in the asset store.
https://www.assetstore.unity3d.com/en/#!/content/13213
![floor_wall_textures](https://cloud.githubusercontent.com/assets/10028115/10703051/9ff963a2-79cd-11e5-9e8a-e58b072f57fe.PNG)

**Comment by benjaminaaron** [comment]
Done for sprint1. Reopen later if necessary.
