### ISSUE TITLE
overall developing strategy

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#6]
The reason why I renamed the newer _develop_ branch (instead of the older _cardboard_ branch) from the [parent repo](https://github.com/accu-rate/SumoVizUnity) into our **master branch** is the following.
I think it will be easier to add the cardboard functionality into the master branch (which does not contain any cardboard-related things at the moment) than to add the **file choosing** and **file loading** architecture to the cardboard branch (which contains only minimal file loading capabilities of an outdated format).
If you think the other way around would have been better - let's discuss, we can still change it :smiley: 

Because of the reasons mentioned in #2 I think we won't have much luck later trying to merge the cardboard branch into the master branch in the hope of easily getting the cardboard part in that way. It will likely be a manual looking-back-and-fort-and-copying-and-adjusting kind of thing... :dancers:

**Comment by benjaminaaron** [comment]
Another major strategic decision is whether or not to stick with the current concept that all visible 3D objects are being created at runtime. Or if some sort of build-system would be nice that imports the 3D objects into the unity editor. That would bring (a lot of) good and bad implications though...

To show the object creation at runtime; notice the object hierarchy on the left in the cardboard branch after opening:

![screen shot 2015-10-17 at 00 34 29](https://cloud.githubusercontent.com/assets/5141792/10554772/eb813136-7466-11e5-970f-75c1a174d0ca.png)

And see how it expands at runtime:

![screen shot 2015-10-17 at 00 34 02](https://cloud.githubusercontent.com/assets/5141792/10554776/f3cae9f4-7466-11e5-9bc0-7a5c58fc0a7c.png)

**Comment by tsiliakis** [comment]
> That would bring (a lot of) good and bad implications though

What would be the concrete implications of that ? As it stands, we have no visual way of developing and are only creating things via C#. I'd be open to discuss an alternative approach.

**Comment by benjaminaaron** [comment]
:heavy_plus_sign: Good would be that we can model stuff directly by pulling it around with the mouse :smiley: 
:heavy_minus_sign: Bad would be that it's not anymore a direct 3D visualisation from a 2D Vadere output. We would optimise our beer tent scene and that's it. New scenarios would have to go through a modelling process first. I guess the idea is though to be able to load new Vadere output files and instantly run it in 3D, no? But maybe we can have both ways - import objects into the unity editor OR create them by script...

As mentioned in #7, I think it would be good if we can find out what @danielbuechele's toolchain was - how did he get the 3D objects into unity? Is there one instance of each type in the scene but invisible maybe?

**Comment by danielbuechele** [comment]
Oh, wow guys. Cool project. I'm on my way to Taipei right now but I'll have a look at your project later and would be happy to help you with any problems.

**Comment by benjaminaaron** [comment]
Oh nice, mentions act as notification even beyond repo-collaborators :bell: 
Hi Daniel! Yes, we are building on your work (and @hacklschorsch's additions rearding google cardboard and parsing XML files) in our semester project _Modellierungsseminar_ with Prof. Köster at hm.edu.
Thanks a lot for offering help! That is likely to be very helpful indeed :smiley: 
Save travels to Taiwan! :airplane:

**Comment by tsiliakis** [comment]
>  I guess the idea is though to be able to load new Vadere output files and instantly run it in 3D, no? 

I think this is the major problem in using precreated objects - we would lose all the ability to create dynamic scenes AFAIK. But it would make our life a lot easier.

**Comment by benjaminaaron** [comment]
One strategy to automatically add 3D objects to a unity scene at editing time (instead of at runtime as it is now) would be to write them into the scene file `.unity` before unity starts. [Here](https://gist.github.com/benjaminaaron/e28ebc979a2b59ca8cfa) the changes made to the `.unity` file by adding a single cube :game_die: 
It would need more digging/experimenting though, there are a bunch of id/hash values in there that I wouldn't know how to generate.

**Comment by benjaminaaron** [comment]
Closing this for now. Reopen if necessary.
