### ISSUE TITLE
build new 3D objects

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/SumoVizUnity#7]
We will need to construct a few new 3D objects like beer **benches**, beer **tables**, a bar, beer **mugs**, pedestrians that are **able to sit** and maybe **look more diverse** than the current one? How/when to trigger sitting (and drinking) **behaviour**? What program to use? How did Daniel Büchele make the 3D objects, can we reproduce his toolchain? :dizzy: 

This task is connected to #4, #5 and #6 :wrench:

**Comment by zumbam** [comment]
I tried to make an table with blender an free modling tool  today.
Here are my results .
Maybe its good enough so we can work with this tool.
The textures I created with photoshop elements 9.

![tischmodelpic](https://cloud.githubusercontent.com/assets/10027929/10566794/e30a00d8-75f0-11e5-89c1-d95403f5a8b2.PNG)

Maybe I show you the file after the next daily scrum so we can discuss about it by the seeing the real file.

**Comment by benjaminaaron** [comment]
Nice work! Importing to unity from Blender should be [well supported](http://docs.unity3d.com/Manual/HOWTO-ImportObjectBlender.html).

**Comment by tsiliakis** [comment]
Looks really good :+1:

**Comment by karimbk** [comment]
Perfect! 👍🏻

**Comment by zippo7** [comment]
Those are the benches and tables we'll be using. They are created in blender and transferred to Unity as Prefabs and will be visible as soon as the ModelCreator works.
![biertisch_bierbank](https://cloud.githubusercontent.com/assets/10028115/10702985/3b7237a6-79cd-11e5-875a-774a2de0215c.PNG)

**Comment by benjaminaaron** [comment]
Awesome, looks great :clap: 
What's the ModelCreator? :smiley:

**Comment by benjaminaaron** [comment]
Closing this for Sprint1. Reopen later for new objects or make new issues.
